name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      appIds:
        description: "AppIds to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - run: |
          echo "Starting process to deploy apps: ${{ github.event.inputs.appIds }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run tests
        run: |
          bash scripts/run_all_unittests.sh

      - name: Install Faros client
        run: |
          npm install -g @faros-ai/cli

      - name: Deploy Apps
        env:
          FAROS_API_KEY: ${{ secrets.FAROS_API_KEY }}
        run: |
          python3 scripts/deploy_apps.py --app_ids "${{ github.event.inputs.appIds }}"
